### ISSUE TITLE
inlining vs writing out to a file

### ISSUE THREAD

**Issue by sa-lee** [vegawidget/virgo#11]
Potential option is to write out to a tempfile to speed up rendering for large datasets.

Options are arrow or csv or json
https://github.com/vega/vega-loader-arrow

**Comment by sa-lee** [comment]
https://vegawidget.github.io/vegawidget/reference/vw_set_base_url.html

**Comment by earowang** [comment]
`serialize_layer_data(v, path)`

**Comment by earowang** [comment]
However, it will not work with knitr, since `vegawidget(base_url)` gives a warning when knitr is in progress.
