### ISSUE TITLE
gadget mode

### ISSUE THREAD

**Issue by sa-lee** [vegawidget/virgo#12]
so I think it would be useful to return the event coordinates (i.e. bounding box of a brush or click event) to the R session, especially for EDA. The only way I think we could do this currently is via shiny. One thought I had would be to have an option that sets viewer to use shiny as a backend with [`runGadget()`](https://shiny.rstudio.com/articles/gadgets.html). This would still run the plot in the rstudio viewer but would allow our plot object to track events.

**Comment by earowang** [comment]
#5
