### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by earowang** [vegawidget/virgo#15]

**Comment by sa-lee** [comment]
Thinking about the vignette and package size, should I reduce the weather data to just be daily or hourly averages? 
It would reduce the package size a bit more and maybe simplify the opening vignette.

Other dataset libraries we could add to suggests:
```
palmerpenguins
gapminder (to show input based selections for the selection vignette)
```

Do you have any other ideas?

**Comment by earowang** [comment]
I sort of like its 15-mins resolution. Can we use the dataset as an external source, and not include it as part of the package to reduce the size. All vignettes are perhaps for the pkgdown website, instead of on cran.

**Comment by sa-lee** [comment]
Ok, it's actually not that large, and if we just make the vignettes pkgdown articles it should be fine!

**Comment by earowang** [comment]
@sa-lee I find the temperature data highly skewed due to all summer months. Perhaps we can include two months (Jan and June in 2020) to show the difference between summer and winter?

**Comment by sa-lee** [comment]
Sure, I can recreate the data, I think it's probably worth having a smaller dataset that only has two months as well.
