### ISSUE TITLE
Scatterplot Matrix

### ISSUE THREAD

**Issue by earowang** [vegawidget/virgo#25]
https://vega.github.io/vega-lite/examples/interactive_splom.html

```r
vega(cars) %>%
  mark_point(enc(x = ac(c(x1, x2, x3)), y = ac(c(y1, y2, y3), vg_mean))) # or supports tidy select
```

The current implementation accepts one variable or a functional form of variable. It needs refactoring to support tidy select.

**Comment by sa-lee** [comment]
I think we will need this for parallel coordinates as well,

```{r}
vega(penguins) %>%
  mark_parcoords(enc(x = c(beak_length_mm:body_mass_g), color = species))
```

**Comment by sa-lee** [comment]
One other idea for verbiage, would be `splice` and to apply a transform `splice_map`

**Comment by earowang** [comment]
`purrr::splice()` 😓

**Comment by sa-lee** [comment]
I think this might need more of a rethink as it requires restructuring the spec quite a bit... :(

**Comment by earowang** [comment]
It could possibly follow the code structure as what we've done with `facet`?

**Comment by sa-lee** [comment]
I'll look into it tomorrow :)

**Comment by earowang** [comment]
The way you implemented `ac()` looks brilliant! 🤩
