### ISSUE TITLE
Grouping aesthetic for line marks

### ISSUE THREAD

**Issue by sa-lee** [vegawidget/virgo#30]
I believe this is called `detail` in vega-lite https://vega.github.io/vega-lite/docs/line.html#line-detail 

Should we implement this as `enc(group = ...)` or leave it as detail?

**Comment by earowang** [comment]
Yes, we've implemented as `group` instead of `detail`. 

https://github.com/vegawidget/virgo/blob/63c1ebd983c334ff58e9f496b5b26a6f930ee611/demo/basics.R#L22-L25

**Comment by sa-lee** [comment]
It doesn't seem to be stacking right for me

```{r}
lex <- gapminder %>% 
  vega(enc(x = year, y = lifeExp, group = country)) %>% 
  mark_line() 
 lex
```
![image](https://user-images.githubusercontent.com/8033857/106537309-28b90280-654e-11eb-9f78-5bae1e04e74d.png)

**Comment by earowang** [comment]
Oops, `detail`, not `details` 😅

**Comment by sa-lee** [comment]
haha gotcha, thanks!
